name: Test on OS

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install
        run: npm ci --no-audit
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
  Windows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install
        run: npm ci --no-audit
        shell: bash
      - name: Build
        run: npm run build
        shell: bash